
version: '3.8'
services:

    # API
    api:
        image: shadowban-tester
        container_name: shadowban-tester-api
        restart: unless-stopped
        build:
            context: .
        depends_on:
          - mongo
        ports:
            - '${PORT}:${PORT}'
        volumes:
            - type: bind
              source: '.'
              target: '/app/'

    # MongoDB
    mongo:
        image: mongo
        container_name: shadowban-tester-mongo
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        ports:
            - 27017:27017
        volumes:
            - type: bind
              source: './mongo/data/'
              target: '/data/db/'
            - type: bind
              source: './mongo/config/'
              target: '/data/configdb/'
